---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackmap-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackmap-api
  template: 
    metadata:
      labels:
        app: stackmap-api
        test: abc
    spec:
      containers:
        - name: stackmap-api
          image: api-rest:latest
          imagePullPolicy: Never
          env:
          - name: PSQLHOST
            value: postgresql.default.svc.cluster.local
          - name: PSQLUSER
            value: postgres
          - name: PSQLDB
            value: postgres 
          - name: PSQLPASS
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgres-password

---

apiVersion: v1
kind: Service
metadata:
  name: psqlapi-service
spec:
  type: NodePort
  selector:
    app: stackmap-api
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3000
      #nodePort: 3000

---
