swagger: "2.0"
info:
  version: "1.0.0"
  title: "Stackmap API"
  description: "API for managing projects and files"
host: "localhost:3000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /login:
    $ref: "./paths/auth.yaml#/~1login"
  /register:
    $ref: "./paths/auth.yaml#/~1register"
  /refresh-token:
    $ref: "./paths/auth.yaml#/~1refresh-token"
  /api/v1/projects:
    $ref: "./paths/projects.yaml#/~1api~1v1~1projects"
  /api/v1/projects/{project_name}:
    $ref: "./paths/project_delete.yaml#/~1api~1v1~1projects~1{project_name}"
  /api/v1/projects/{project_name}/files:
    $ref: "./paths/files.yaml#/~1api~1v1~1projects~1{project_name}~1files"
