swagger: "2.0"
info: 
  version: "1.0.0"
  title: "Stackmap API"
  description: "Query and push Stackmap related products"
  #termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Someone"
  license: 
    name: "MIT"
host: "localhost:3000"
basePath: "/api/v1/"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /products: 
    $ref: ./paths/products.yaml
  /times:
    $ref: ./paths/times.yaml
  