
get: 
  description: "Return available products"
  produces: 
    - "application/json"
  responses: 
    "200":
      description: "A list of products."
      schema: 
        type: "object"
        properties:
          uniquelayers:
            type: array
            items:
              type: string
